name: example
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  text_editor:
    path: ../
  flutter_markdown: ^0.4.3

flutter:
  uses-material-design: true
